### PR TITLE
Add the loading of save data

### PR DESCRIPTION
**Pull request by ghost**
Hello again. I've been working on this for a while now and I've finally got it to a bug-free state. Seeing as you're working on version 2.0, I tried to get this done as fast as possible so that it could be added in the next version.

All methods related to the score are located in the "score.c" file, as well as a really basic Level Up feature that only changes the text from "Point" to everything including "Hexagon", like the actual game. It currently loads save files from "/3DS/SuperHaxagon/savedata/" as .txt files. I could probably change it into a harder to edit format, but since there's no advantage to changing your high score, its not the highest priority at the moment. 

I feel kinda bad since I've changed a lot of your code, but I hope it's not too hard to understand my code. I made a couple comments as well as tried to use as little code as possible to ensure that it was somewhat easy to understand in the end. If you have any questions or want me to change something, feel free to ask.

### CODE REVIEW

**Comment by ghost** [comment]
By the way, your current 2.0 code, as you suspected, does not compile.

**Comment by RedTopper** [comment]
Unfortunately I have no idea how I am going to merge this and version 2.0... This update is going to have to wait because almost everything was changed or refactored into other files. Once I finish refactoring the code I'll have to merge this manually!

> By the way, your current 2.0 code, as you suspected, does not compile.

For the most part I am coding version 2.0 completely blind because I am refactoring everything at once (not small sections). Once the code is restored, I'll merge your commit and resolve all of the conflicts (there will be a lot)! Because of this, literaly zero code in the version 2.0 branch has been tested, so we'll see how that goes. 

Sidenote: for game data I'm going to be using the path as defined here: https://github.com/RedInquisitive/Super-Haxagon/blob/2.0/source/levels.c#L16 so you can save your score data there along with the level files and music.

**Comment by ghost** [comment]
Alright, thats fine. I'll change the directory when I can. Quick question regarding the custom levels: how will they be loaded? Like, do they replace one of the 6 existing levels, or are they added to the total number of levels? I'd like to know so I can adapt my code accordingly. Thanks.

**Comment by RedTopper** [comment]
They are created using https://github.com/RedInquisitive/Haxa-Editor, a cross platform GUI tool that will allow you to edit and export levels. This tool is 100% functional, so if you are familiar with any java development environment it should compile without issues (I'll create a standalone JAR file when the format is official, I still need to tweak a few things).

I will re-create all of the "base levels" using this tool. In order to "share" a level, you'll need to share your (levelname).head file and all of the linked (patternname).ptn files. Somebody can then export the levels to the  "levels.haxagon" format (it's one click on the main menu of the application) and copy the exported file to the 3DS's SD card. The format itself is in binary and can be reverse engineered by looking at the source code.

With this system, anyone can share individual patterns for somebody to use, or entire levels! This also means that you can have (or can create) as many levels as you want. You will no longer be limited to just super "hexagon", but you could create super "pentagon", super "triangle" or super "hexadecagon" if you want.

In version 2.0, the generic struct for the level metadata is here: https://github.com/RedInquisitive/Super-Haxagon/blob/2.0/source/types.h#L50-L68

**Comment by RedTopper** [comment]
@jmanplaysgames As an update for you: I have dynamic level loading working, as well  as the main menu. I have yet to refactor the base game, so I'll give you another shutout when that  happens. I don't know if you want me to refactor your code for v2.0 or if you want to do it yourself. Just let me know!

**Comment by RedTopper** [comment]
@jmanplaysgames Hey, if you ever get the time, try out the 2.0 branch and tell me what you think. It's not ready for release, but it's pretty close!

There's only 1 level atm.

**Comment by ghost** [comment]
Im closing this pull request to make another, GitHub is being wierd and wont let me commit the latest 2.0 changes to my fork, No idea why.

**Comment by ghost** [comment]
I will open a new pull request once I get everything sorted out.

**Pull request closed without merging**
