### PR TITLE
Linux/Mac Building + Other Improvements

### PR DESCRIPTION
**Pull request by videah**
This should make it possible to build on Linux and Mac, and has a generally much cleaner way of building a CIA.

I've only tested it on Linux, but my changes should work on other platforms too.

### CODE REVIEW

**Comment by RedTopper** [comment]
Fantastic, I had no idea how Makefiles worked anyway.

**Comment by RedTopper** [comment]
I have questions (I don't know if either can be accomplished)!
1. Due to my lack of knowledge on Makefiles, if I wanted to add back the ability to quickly copy the CIA to my OwnCloud so I can use a QR code to upload it during development, how would I do that? (this will not be pushed to the repo, i'd be just for me this time)
2. Also, would it be possible to have a make flag that can make it with the ./romfs/music folder so the normal upload size is smaller for tests? Right now I just manually remove the music, but if "make bgm" was an option, that would be even better.

**Comment by RedTopper** [comment]
It does work on my windows machine btw

**Comment by videah** [comment]
1. You might just want a bash script for that, and add it in your .gitignore
2. Not that I'm aware of

**Pull request merged**
